name: "Business Central AI Code Reviewer (Continue + MCP)"
description: "Run an AI-powered, Business Central specific code review on a Pull Request using OpenAI, Azure OpenAI or OpenRouter.ai."
branding:
  icon:  'package'
  color: 'orange'
author: "Aident GmbH"
version: "2.0.0"

inputs:
  GITHUB_TOKEN:
    description: "GitHub token with repo-scope"
    required: true
    type: string

  # Continue (Hub) + Model
  CONTINUE_API_KEY:
    description: "Continue Hub API key"
    required: true
    type: string
  CONTINUE_CONFIG:
    description: "Hub slug for your reviewer (e.g. aident/bc-pr-reviewer or continuedev/review-bot)"
    required: false
    default: "continuedev/review-bot"
    type: string

  # Review behaviour
  APPROVE_REVIEWS:
    description: "Let the bot approve / request-changes (based on AI output 'suggestedAction')"
    type: boolean
    default: false
  MAX_COMMENTS:
    description: "Max inline comments to post (0 = unlimited; GitHub caps single PR at 1000)."
    type: number
    default: 10

  # Context customization
  PROJECT_CONTEXT:
    description: "Architecture / guidelines text"
    type: string
    default: ""

  CONTEXT_FILES:
    description: "Comma-separated globs fetched for context"
    type: string
    default: ""

  INCLUDE_PATTERNS:
    description: "Comma-separated globs to include in review"
    type: string
    default: "**/*.al,**/*.xlf,**/*.json"

  EXCLUDE_PATTERNS:
    description: "Comma-separated globs to exclude"
    type: string
    default: ""

  # Fetch linked issues (optional context)
  ISSUE_COUNT:
    description: "Max linked issues to fetch (0 = all)"
    type: number
    default: 0
  FETCH_CLOSED_ISSUES:
    description: "Include closed issues as context"
    type: boolean
    default: true

  # App autodiscovery
  AUTO_DETECT_APPS:
    description: "Enable automatic app.json discovery"
    type: boolean
    default: true
  INCLUDE_APP_PERMISSIONS:
    description: "Include *.PermissionSet.al / *.Entitlement.al from each app"
    type: boolean
    default: true
  INCLUDE_APP_MARKDOWN:
    description: "Include *.md files from each app"
    type: boolean
    default: true

  # Prompt style
  BASE_PROMPT_EXTRA:
    description: "Free-form text injected into the reviewers prompt (optional)"
    type: string
    default: ""
  LOG_PROMPT:
    description: "Log prompt JSON (redacted) to runner logs"
    type: boolean
    default: false

runs:
  using: composite
  steps:
    - name: Setup Node.js (v20)
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install helpers parse-diff
      shell: pwsh
      working-directory: ${{ github.action_path }}
      run: |      
        npm install --no-save parse-diff@latest

    - name: Install Continue CLI
      shell: pwsh
      run: |      
        npm i -g @continuedev/cli

    # (Optional) Install uv so Serena MCP can be launched by Continue if your config uses uvx
    - name: Install uv (for Serena MCP, optional)
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh || true
        echo "$HOME/.local/bin" >> $GITHUB_PATH || true

    - name: Run cn (super simple)
      env:
        CONTINUE_API_KEY: ${{ inputs.CONTINUE_API_KEY }}
        CONTINUE_LOG_LEVEL: debug
      shell: bash
      run: |
        set -euxo pipefail
        mkdir -p .continue-logs
        # Use `script` to force a PTY; some CLIs only flush when attached to a TTY.
        script -q -e -c \
          'cn --config continuedev/review-bot --auto -p "Return ONLY the string OK"' \
          .continue-logs/cn.tty.log
        # Also capture raw stdout/stderr via redirection (no TTY) for comparison
        stdbuf -oL -eL cn --config continuedev/review-bot --auto \
          -p "Return ONLY the string OK" \
          > .continue-logs/cn.stdout.txt 2> .continue-logs/cn.stderr.txt || echo "exit=$?" >> .continue-logs/cn.stderr.txt
        echo "---- STDOUT ----"; cat .continue-logs/cn.stdout.txt || true
        echo "---- STDERR ----"; cat .continue-logs/cn.stderr.txt || true

    - name: Run AI Code Review (Continue + MCP)
      shell: pwsh
      env:
        # Continue config may launch MCP servers that look for these env vars.
        GITHUB_TOKEN:                 ${{ inputs.GITHUB_TOKEN || github.token }}
        GITHUB_PERSONAL_ACCESS_TOKEN: ${{ inputs.GITHUB_TOKEN || github.token }}
        CONTINUE_API_KEY:             ${{ inputs.CONTINUE_API_KEY }}
        CONTINUE_CONFIG:              ${{ inputs.CONTINUE_CONFIG }}
      run: |
        $params = @{
          GitHubToken           = "${{ inputs.GITHUB_TOKEN || github.token }}"
          MaxComments           = [int]"${{ inputs.MAX_COMMENTS }}"
          ProjectContext        = "${{ inputs.PROJECT_CONTEXT }}"
          ContextFiles          = "${{ inputs.CONTEXT_FILES }}"
          IncludePatterns       = "${{ inputs.INCLUDE_PATTERNS }}"
          ExcludePatterns       = "${{ inputs.EXCLUDE_PATTERNS }}"
          IssueCount            = [int]"${{ inputs.ISSUE_COUNT }}"
          FetchClosedIssues     = [bool]::Parse("${{ inputs.FETCH_CLOSED_ISSUES }}")
          AutoDetectApps        = [bool]::Parse("${{ inputs.AUTO_DETECT_APPS }}")
          IncludeAppPermissions = [bool]::Parse("${{ inputs.INCLUDE_APP_PERMISSIONS }}")
          IncludeAppMarkdown    = [bool]::Parse("${{ inputs.INCLUDE_APP_MARKDOWN }}")
          BasePromptExtra       = "${{ inputs.BASE_PROMPT_EXTRA }}"
        }
        if ("${{ inputs.APPROVE_REVIEWS }}" -eq "true") { $params.ApproveReviews = $true }
        if ("${{ inputs.LOG_PROMPT }}" -eq "true")      { $params.LogPrompt      = $true }

        & "${{ github.action_path }}/scripts/continue-review.ps1" @params

    - name: Upload Continue logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: continue-cli-logs
        path: |
          .continue-logs/continue_cli_raw.log
          .continue-logs/continue_cli_stdout.txt
          .continue-logs/continue_cli_stderr.txt
        if-no-files-found: warn
        retention-days: 7
