name: Self-test the AI Code Reviewer

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write
  issues: read

jobs:
  self_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run AI Code Reviewer on this repo
        uses: ./
        with:
          GITHUB_TOKEN:        ${{ secrets.GITHUB_TOKEN }}
          AI_PROVIDER:         azure
          AI_MODEL:            ${{ secrets.AZURE_ENDPOINT }}
          AI_API_KEY:          ${{ secrets.AZUREOPENAIKEYO3MINI }}
          MAX_COMMENTS:        10
          DIFF_CONTEXT_LINES:  25
          APPROVE_REVIEWS:     false

          # --- tailor the prompt & context ---
          BASE_PROMPT_EXTRA: |
            You are **NOT** reviewing AL code for Microsoft Dynamics 365 Business Central.
            You are reviewing a **GitHub composite action** written
            in PowerShell 7 and YAML.  
            Focus on best practices for:
              - input/secret handling  
              - failure behaviour and logging  
              - idempotency and step isolation  
              - cross-platform PowerShell quirks  
              - clarity & maintainability of the README/docs.
            Ignore Microsoft Business Central guidelines.

          PROJECT_CONTEXT: |
            This repository provides a reusable PowerShell composite
            action that calls an LLM to perform PR reviews.
            Key goals: minimise noise, fail fast on huge diffs,
            follow GitHub Marketplace conventions.

          DISABLE_GUIDELINEDOCS:  true     # skip AL-Guideline fetch
          AUTO_DETECT_APPS:       false    # we are not in a BC app repo

          # limit the diff scope to PowerShell & workflow files
          INCLUDE_PATTERNS:       "**/*.ps1,**/*.yml,**/*.yaml"
          EXCLUDE_PATTERNS:       ""

          # don’t pull closed issues into the prompt
          FETCH_CLOSED_ISSUES:    false
